- .github/renovate.json5
- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can be helpful as well.
> Add `.github/renovate.json5`

- .changeset/chilled-swans-kneel.md
- package.json
- src/printer.js
- src/utils.js
- yarn.lock
A fix for the last version of the parser
> Fix for @astrojs/parser 0.20.2

- .changeset/shiny-countries-develop.md
- src/utils.js
- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can be helpful as well.
> Add support for prettier-ignore comments

- .github/workflows/ci.yml
- Fixes #50
- Adds testing on Windows and macOS to the CI action
> Setup Windows and macOS testing

- .changeset/loud-poems-grow.md
- src/printer.ts
- test/astro-prettier.test.ts
- test/fixtures/format-nested-sass-style-tag-content/input.astro
- test/fixtures/format-nested-sass-style-tag-content/output.astro
- test/fixtures/format-nested-style-tag-content/input.astro
- test/fixtures/format-nested-style-tag-content/output.astro
Fixes #40
Added a couple of tests for nested style tags including one for sass.
> Format nested style tag content

- .changeset/polite-elephants-call.md
- src/nodes.ts
- src/printer.ts
- test/astro-prettier.test.ts
- test/fixtures/spread-operator/input.astro
- test/fixtures/spread-operator/output.astro
Fixes #65 
I added a test for this.
> Format spread operator

- README.md
Update links in README.md
N/A
N/A
> Update links README.md

- .changeset/rotten-trees-flash.md
- package.json
- yarn.lock
> Bump ava to v4.0.1

- .changeset/tasty-vans-travel.md
- src/printer.ts
- test/fixtures/embedded-in-markdown/output.md
- test/fixtures/option-html-whitespace-sensitivity-ignore/input.astro
- test/fixtures/option-html-whitespace-sensitivity-ignore/output.astro
- test/fixtures/option-html-whitespace-sensitivity-strict/input.astro
- test/fixtures/option-html-whitespace-sensitivity-strict/output.astro
- test/fixtures/preserve-tag-case/input.astro
- test/fixtures/preserve-tag-case/output.astro
The plugin will always format HTML instead of conditionally.
Fixes #75 
I change some tests see the comments.
> Format html using only the plugin itself

- .changeset/short-years-bake.md
- src/printer.ts
- src/utils.ts
- test/astro-prettier.test.ts
- test/fixtures/nested-comment/input.astro
- test/fixtures/nested-comment/output.astro
Fixes #81 
I added a test for nested comments.
> Fix comment error when nested

- .changeset/pre.json
- .github/workflows/ci.yml
- .github/workflows/format.yml
- .github/workflows/prerelease.yml
- package.json
- src/nodes.ts
- src/parse.ts
- src/printer.ts
- src/syncUtils.ts
- src/utils.ts
- test/astro-prettier.test.ts
- test/fixtures/fragment/input.astro
- test/fixtures/fragment/output.astro
- test/fixtures/single-style-element-with-sass-lang/input.astro
- test/fixtures/single-style-element-with-sass-lang/output.astro
- test/fixtures/single-style-element-with-scss-lang/input.astro
- test/fixtures/single-style-element-with-scss-lang/output.astro
- test/fixtures/style-tag-attributes/input.astro
- yarn.lock
> [WIP] Add new compiler

- .github/workflows/ci.yml
- package.json
> Remove node 12 from ci

- .changeset/sweet-cameras-build.md
- .eslintrc
- .prettierrc.json
- src/nodes.ts
- src/options.ts
- src/printer.ts
- src/utils.ts
- test/test-utils.ts
- test/tests/basic.test.ts
- test/tests/markdown.test.ts
- test/tests/options.test.ts
- test/tests/other.test.ts
- test/tests/styles.test.ts
- Changes prettier width from 180 to 80
> Change prettier width

- CONTRIBUTING.md
- README.md
- Updates to the readme and contributing
> Update readme & contributing

- .changeset/violet-books-try.md
- src/nodes.ts
- src/printer.ts
- src/utils.ts
- test/fixtures/basic/html-comment/input.astro
- test/fixtures/basic/html-comment/output.astro
- test/tests/basic.test.ts
- test/tests/other.test.ts
- Adds a new line after comments
- Added test
> Add new line after comments

- test/test-utils.ts
- test/tests/options.test.ts
- Small refactor of test-utils
> Refactor test-utils

- README.md
**This PR should be merged _AFTER_** https://github.com/withastro/.github/pull/2
- This PR updates links to GOVERNANCE and FUNDING files which will move once https://github.com/withastro/.github/pull/2 is merged
n/a
n/a
> Update links to community docs

- .changeset/gorgeous-coins-hide.md
- src/nodes.ts
- src/printer.ts
- test/fixtures/other/slots/input.astro
- test/fixtures/other/slots/output.astro
- test/tests/other.test.ts
> Self-close slots

- .changeset/gold-cherries-kiss.md
- src/printer.ts
- test/fixtures/options/option-jsx-single-quote-false/input.astro
- test/fixtures/options/option-jsx-single-quote-false/options.json
- test/fixtures/options/option-jsx-single-quote-false/output.astro
- test/fixtures/options/option-jsx-single-quote-true/input.astro
- test/fixtures/options/option-jsx-single-quote-true/output.astro
- test/fixtures/options/option-single-quote-false/input.astro
- test/fixtures/options/option-single-quote-false/output.astro
- test/fixtures/options/option-single-quote-true/input.astro
- test/fixtures/options/option-single-quote-true/output.astro
- test/tests/options.test.ts
- yarn.lock
Just rebased https://github.com/withastro/prettier-plugin-astro/pull/195, all credits to the author of the PR
N/A
N/A
> HTML attribute quotes now depend on jsxSingleQuote option

- .changeset/calm-geese-rescue.md
- src/printer.ts
- test/fixtures/options/option-semicolon-false/input.astro
- test/fixtures/options/option-semicolon-false/output.astro
- test/fixtures/options/option-semicolon-true/input.astro
- test/fixtures/options/option-semicolon-true/output.astro
- Fixes #169
- Change a couple of tests.
> Use prettier option 'semi' for jsx semi colons

- .changeset/happy-sheep-shave.md
- src/printer.ts
- test/fixtures/options/single-attribute-per-line-false/input.astro
- test/fixtures/options/single-attribute-per-line-false/options.json
- test/fixtures/options/single-attribute-per-line-false/output.astro
- test/fixtures/options/single-attribute-per-line-true/input.astro
- test/fixtures/options/single-attribute-per-line-true/options.json
- test/fixtures/options/single-attribute-per-line-true/output.astro
- test/tests/options.test.ts
- Closes #190 
- Added a couple of tests
> Use Prettier option: 'singleAttributePerLine'

- .changeset/curvy-forks-knock.md
- src/printer/index.ts
- test/fixtures/basic/html-custom-elements/input.astro
- test/fixtures/basic/html-custom-elements/output.astro
- test/tests/basic.test.ts
Fix the parser crashing when trying to format a component with custom elements
Added a test
N/A
> Fix not being able to format custom elements

- .changeset/old-dogs-pump.md
- package.json
- yarn.lock
Update to latest compiler version
Fix https://github.com/withastro/prettier-plugin-astro/issues/269
All tests still pass, tested manually
N/A
> Update compiler version

- .changeset/friendly-taxis-talk.md
- package.json
- yarn.lock
Does what it says
Checking CI
N/A
> chore: upgrade compiler

- package.json
- test/fixtures/other/ignore-self-close/input.astro
- test/fixtures/other/ignore-self-close/output.astro
- test/tests/other.test.ts
- yarn.lock
Title is self-explanatory! 
No changeset is needed, there was already a changeset for this added in a previous PR
Fix #306
It's a test!
N/A
> Add test for ignoring self-closing tag + upgrade compiler

- .changeset/wet-needles-cheer.md
- src/printer/embed.ts
- test/fixtures/other/spread-attributes/input.astro
- test/fixtures/other/spread-attributes/output.astro
- test/tests/other.test.ts
Added support for formatting spread attributes, this works very similarly to expression attributes so not much to say
Fix https://github.com/withastro/prettier-plugin-astro/issues/318
Added a test
N/A
> Add support for formatting spread attributes

- .changeset/six-lobsters-jog.md
- src/printer/utils.ts
- test/fixtures/basic/html-class-attribute-with-line-breaks/input.astro
- test/fixtures/basic/html-class-attribute-with-line-breaks/output.astro
- test/tests/basic.test.ts
See https://github.com/withastro/prettier-plugin-astro/issues/368
> Do not delete line breaks and indentation of lines in class attribute

- .changeset/selfish-worms-press.md
- src/printer/embed.ts
- test/fixtures/other/non-jsx-compatible-characters/input.astro
- test/fixtures/other/non-jsx-compatible-characters/output.astro
- tsconfig.json
What the title says!
Added a test case
N/A
> fix(embed): Replace all instances of invalid characters inside expressions

- .changeset/smart-bats-attack.md
- src/printer/index.ts
- test/fixtures/other/clean-self-closing/input.astro
- test/fixtures/other/clean-self-closing/output.astro
- test/tests/other.test.ts
A mistake slipped in in the PR to convert to Prettier 3, this fixes that
Fix https://github.com/withastro/prettier-plugin-astro/issues/359
Added a test
N/A
> fix: regression with self-closing tags text
