withastro/prettier-plugin-astro

src/printer.js, test/astro-prettier.test.mjs
The reason why this bug occurred is a type error of empty element.  
This PR enables the user to format .astro files like this.  
```
---
import Color from "../components/Color.jsx";
let title = "My Site";
const colors = ["red", "yellow", "blue"];
---
<!DOCTYPE html>
<html lang="en">
<head>
<title>My site</title>
</head>
<body>
<h1>{title}</h1>
{"I'm some super long text and oh boy I sure do hope this formatter doesn't break me!"}
{colors.map((color) => <div>
<Color name={color} />
</div>)}
</body>
</html>
```
=> [Bug Fix]: can't format an Astro file with a `<!DOCTYPE html>` + embedded JSX expressions

src/printer.js, test/astro-prettier.test.mjs, test/fixtures/in/preserve-tag-case.astro, test/fixtures/in/with-script.astro, test/fixtures/out/preserve-tag-case.astro, test/fixtures/out/with-script.astro
Fixes #4
While fixing this I encounter an error with the test "with-script", so I also fix that.
=> Preserve tag case

src/printer.js, test/astro-prettier.test.mjs, test/fixtures/out/with-codespans.astro
- Adds support for formatting Codefences `\`\`\`js` as opposed to naively printing them like we do today.
=> Add support for formatting CodeFences w/in `<Markdown/>`

.changeset/cool-donuts-buy.md, src/printer.js, src/utils.js, test/astro-prettier.test.mjs, test/fixtures/in/with-codespans.astro, test/fixtures/out/with-codespans.astro
Allows Prettier formatting within `<Markdown>` components
Tests added; tests should pass
No documentation needed
=> Add support for styling within Markdown component

.eslintrc, .gitpod.yml, README.md
- Adds `yarn build` to contributing instructions + a link to the ava testing docs
- Adds `yarn build` to the `.gitpod.yml` setup so that prebuilds work again
- Adds `test/**` to the eslint so that we can lint for ava lint errors using `plugin:ava/recommended`
Marginally improved contributing docs - CONTRIBUTING.md should probably be a thing!
=> Update repo setup wrt (Typescript Refactor #38)

.changeset/swift-scissors-swim.md, src/options.ts, src/printer.ts, src/utils.ts, test/astro-prettier.test.ts, test/fixtures/option-astro-allow-shorthand-false/input.astro, test/fixtures/option-astro-allow-shorthand-false/options.json, test/fixtures/option-astro-allow-shorthand-false/output.astro, test/fixtures/option-astro-allow-shorthand-true/input.astro, test/fixtures/option-astro-allow-shorthand-true/options.json, test/fixtures/option-astro-allow-shorthand-true/output.astro
Adds a new option (astroAllowShorthand) to disable automatic shorthand. It's enabled by default. Closes #39 
```astro
<BaseLayout title={title}>
```
```astro
<BaseLayout {title}>
```
I added tests for each value of the new option.
=> Add new Astro option: 'allow shorthand'

.changeset/quick-emus-whisper.md, src/printer.ts, test/astro-prettier.test.ts, test/fixtures/markdown-component-content/input.astro, test/fixtures/markdown-component-content/output.astro
Fixes the format of markdown inside a markdown component.
Fixes #41
Fixes #42
I added an extra test.
=> Format markdown component content

.changeset/nice-impalas-live.md, src/printer.ts, src/utils.ts, test/fixtures/option-astro-allow-shorthand-false/input.astro, test/fixtures/option-astro-allow-shorthand-false/output.astro, test/fixtures/option-astro-allow-shorthand-true/input.astro, test/fixtures/option-astro-allow-shorthand-true/output.astro
Fixes #87.
Note: Formatting might be off, because I worked on windows and new lines are problematic, so I ended up not running `yarn format`
Modified the `option-astro-allow-shorthand-false` test to include a shorthand, and expecting a binary expression.
Bug fix only
=> Fix shorthand attributes incorrectly converted to strings.

.changeset/selfish-cherries-grab.md, src/options.ts, test/fixtures/converts-to-shorthand/input.astro, test/fixtures/converts-to-shorthand/output.astro, test/fixtures/style-tag-attributes/output.astro, test/tests/other.test.ts
Shorthand removes attribute keys and breaks Typescript which is used by Astro. It's also uncommon and should be disabled by default, and only opt-in for those that specifically want it.
- Sets `astroAllowShorthand` to default `false`
No new tests.
No documentation to update.
=> set `astroAllowShorthand` to default off

.changeset/stale-terms-help.md, vitest.config.ts
- Disables vitest multi-threading. It was causing a lot of crashes.
=> Disable vitest multi-threading

.changeset/moody-queens-fail.md, src/printer.ts, src/utils.ts, test/fixtures/basic/simple-text/input.astro, test/fixtures/basic/simple-text/output.astro, test/tests/basic.test.ts, test/tests/other.test.ts
- Removes duplicated text nodes from the ast.  Currently, the compiler has a bug that duplicates text nodes when no tag-like node elements are present.
- Test added
=> Fix: duplicate text

.changeset/shaggy-pots-doubt.md, package.json, test/fixtures/other/spread-operator/input.astro, test/fixtures/other/spread-operator/output.astro, yarn.lock
Fixes #193.
This PR updates `@astrojs/compiler` to fix #193 issue.
See https://github.com/withastro/compiler/pull/414 for details on fixing the compiler.
I modified the test case for the spread attribute to check that #193 issues were resolved.
bug fix only
=> Update @astrojs/compiler and fix for spread in expression

.changeset/curly-pigs-live.md, src/printer.ts, src/utils.ts, test/fixtures/other/embedded-expr/input.astro, test/fixtures/other/embedded-expr/output.astro
Fix the error in jsx empty expression.
Related to https://github.com/withastro/prettier-plugin-astro/issues/193#issuecomment-1145127337.
I added JSX empty expression to the fixture for testing embedded expressions.
bug fix only
=> fix for jsx empty expression

package.json, rollup.config.js, src/index.ts, src/utils.ts, vitest.config.ts, yarn.lock
During development, there was some errors inside certain files due to certain dependencies being outdated. I figured updating everything would in general improve the situation, so I did. This allow us to benefit from Prettier's new caching system, which is pretty neat. I also removed some unused dependencies which were copy-pasted from the Svelte plugin, I think
Additionally, at build Rollup would warn us about certain dependencies being automatically excluded, we now specify those dependencies manually so there's no warning anymore
Ran tests locally and used plugin locally to confirm Rollup and its plugin updates didn't break everything
N/A
=> Update dependencies and fix rollup warnings

.changeset/wild-pugs-repair.md, package.json, src/printer.ts, src/utils.ts, yarn.lock
- Removes a utility. Fixed in https://github.com/withastro/compiler/pull/429
=> Remove dedup utility

README.md
Update the syntax of `documentSelectors` to use an array, as it should. Removed documentation of `astroSortOrder` setting that is currently not working. (Maybe we don't really need to support it, to be honest. It makes more sense inside Svelte components or Vue ones that it does in Astro)
N/A
N/A
=> Fix `documentSelectors` syntax, remove not working option from README

.changeset/purple-mangos-drum.md, .eslintrc, src/printer/embed.ts, test/fixtures/other/shorthand-in-expression/input.astro, test/fixtures/other/shorthand-in-expression/output.astro, test/tests/other.test.ts
This PR does two things:
- Fixed shorthands props not working in expression. This is a more complicated issue than it might seems because inside expressions, we use a TypeScript parser and as such, Astro-isms will cause a parsing error. I solve this by first transforming the expression into a JSX compatible one and then re-adding the Astro-ism once it's formatted
- Changed how error handling works when we can't parse an expression, now the plugin will report the error, but won't actually fail. Instead the node will be left as-is. This is consistant with how other Prettier plugins work (ex: the Svelte one does this, so does the official MDX one (I believe?)). If `PRETTIER_DEBUG=1` is set, then the plugin will throw like before (just like official Prettier plugins does)
Both changes didn't …
=> Fix shorthand props not working inside expressions and update error handling

.changeset/stupid-peas-mate.md, src/printer/embed.ts
Further work on error handling after a night of sleep after https://github.com/withastro/prettier-plugin-astro/pull/246
This PR makes it so we throw and provide a good error message on parsing fails, why the change of mind from the previous PR where I decided not to throw?
- I figured how to throw with a good error message
- Explicit errors are better so users can help us figure it out when it's our fault the parsing failed
- Better experience in VS Code (the Prettier icon change to a warning sign when it couldn't parse)
Also, with this PR the behaviour is now consistent between the frontmatter / script tags and expressions
Before
After
(The TypeScript's parsers error are really good looking, might be inspiration for `astro check` 🤔)
N/A, I think? Testing that the TypeScript or Babel …
=> More consistent error handling, properly throw with good error message on parsing fail

.changeset/quiet-dots-thank.md, src/printer/embed.ts
Add a try catch around the CSS parsing to handle errors properly like we do for the frontmatter and script tags
Fix https://github.com/withastro/prettier-plugin-astro/issues/215
Tested manually
N/A
=> Properly handle errors inside style tags

.changeset/silent-laws-attack.md, src/index.ts, src/printer/utils.ts
Add a fallback to our workers resolutions to support loading them non-relative to `import.meta.url`. This is needed for when another plugin uses our parser (ex: this is needed for `prettier-plugin-tailwindcss` support 😄)
Looking forward to not needing those workers at all when Prettier 3 lands 👼
Tested manually, tests still pass
N/A
=> Support resolving a non-relative path for workers

.changeset/good-cougars-explain.md, src/printer/index.ts, src/printer/utils.ts, test/fixtures/basic/html-class-attribute/input.astro, test/fixtures/basic/html-class-attribute/output.astro, test/tests/basic.test.ts
Prettier's HTML printer does this. So we should also do it! Also, this is needed to make us pass `prettier-plugin-tailwindcss`'s test suite 👼 
Added a test
N/A
=> Trim the class attribute

.changeset/swift-books-melt.md, src/printer/embed.ts, test/fixtures/other/typescript-expression/input.astro, test/fixtures/other/typescript-expression/output.astro, test/tests/other.test.ts
A bit unfortunate, but this essentially revert a lot of what I did in https://github.com/withastro/prettier-plugin-astro/pull/255 regarding the `__js_expression` parser. However, I found another way to achieve the same result, so not all is lost!
Fix https://github.com/withastro/prettier-plugin-astro/issues/259
Added a test, tests still pass
N/A
=> Fix TypeScript not working inside expression

.changeset/grumpy-paws-grab.md, src/printer/index.ts, test/fixtures/basic/self-closing/input.astro, test/fixtures/basic/self-closing/output.astro, test/tests/basic.test.ts
Correctly break self-closing tags with attributes onto multiple lines when necessary.
Fixes #142
=> Correctly break long self-closing tags

.changeset/beige-geckos-speak.md, README.md, src/printer/utils.ts, test/fixtures/basic/inline-whitespace/input.astro, test/fixtures/basic/inline-whitespace/output.astro, test/test-utils.ts, test/tests/basic.test.ts
Implement end tag hugging for inline elements containing text not ending in whitespace. This was actually already partially implemented, but uncommenting caused another test to fail because it was incorrectly hugging on non-text contents as well.
Also fixed some small typos.
Fixes #263
=> Don't add whitespace to inline elements

.changeset/breezy-bags-matter.md, src/printer/embed.ts, src/printer/utils.ts, test/fixtures/other/non-jsx-compatible-characters/input.astro, test/fixtures/other/non-jsx-compatible-characters/output.astro, test/tests/other.test.ts
Just like with shorthands props, we need to do some transformations inside expressions to make sure we support things that re valid in Astro but not compatible with JSX. 
Added a test
N/A
=> Add support for formatting elements with attributes not compatible with JSX

.changeset/chilly-donkeys-peel.md, src/printer/index.ts, test/fixtures/options/single-attribute-per-line-false/input.astro, test/fixtures/options/single-attribute-per-line-false/output.astro, test/fixtures/options/single-attribute-per-line-true/input.astro, test/fixtures/options/single-attribute-per-line-true/output.astro
Previously, we were missing a hardline between the attributes and the closing bracket of the opening tag on inline elements when using singleAttributePerLine. This fix that
Fix https://github.com/withastro/prettier-plugin-astro/issues/281
Updated tests for this
N/A
=> Add a hardline after attributes on inline elements when using singleAttributePerLine

.changeset/warm-dots-type.md, src/printer/index.ts, src/printer/utils.ts, test/fixtures/other/directive/input.astro, test/fixtures/other/directive/output.astro
This PR makes it so any elements that has `set:*` directives can be allowed to self close (provided that it's empty)
Updated tests with this
N/A
=> Allow elements with set:* directives to self-close

.changeset/lucky-cows-applaud.md, src/printer/index.ts, src/printer/utils.ts, test/fixtures/options/option-jsx-single-quote-true/input.astro, test/fixtures/options/option-jsx-single-quote-true/output.astro
In JSX, `jsxSingleQuote` is only taken into account when the attribute value does not contain any single quotes (and vice versa for double quotes). This makes it so we follow this behaviour too
Fix https://github.com/withastro/prettier-plugin-astro/issues/291
Updated test to account for this
N/A
=> Fix jsxSingleQuote not considering the inner quotes like JSX

.changeset/clean-games-yawn.md, src/printer/embed.ts, test/fixtures/other/expression-multiple-roots/input.astro, test/fixtures/other/expression-multiple-roots/output.astro, test/tests/other.test.ts
This is a bit of a Not Worst Than What We Had Before situation, as I found a way to correct the expressions so they can be parsed by Prettier's JavaScript parsers, however I couldn't figure out a way to "uncorrect" them so they're "Astro-like".
I tried a bunch of things, but they had all downsides such as the indentation being wrong, not working in some cases, messing up the formatting somewhere else etc.
In my opinion, it formatting clumsily in a consistant way is better than it crashing and failing to format the entire file. So, hey, it's an improvement
Fix https://github.com/withastro/prettier-plugin-astro/issues/238
Before
```astro
{hello ?? <div></div><div></div>}
```
After
```astro
{
hello ?? (
<>
<div />
<div />
</>
)
}
```
Added a test for this
N/A
=> Support formatting expressions with multiple roots

.changeset/tiny-parents-refuse.md, src/printer/index.ts, test/fixtures/basic/html-custom-elements/output.astro
Thank you @getflourish for reporting this issue!
According to the HTML Spec, custom elements are not allowed to self-close
In Astro it doesn't really matter, since the compiler will self close them anyway, but as a formatter we generally try to output compliant HTML (also this is how it is in other Prettier plugin, so might as well be consistent)
Similarly to other tags that are traditionally not able to self close, adding a `set:*` directive will allow them to self close even then
Updated tests
N/A
=> Don't allow custom-elements to self close

README.md
- What does this change?
File extension using for Prettier config file.
I tried to use Prettier to format a .astro file on VS Code and this was the output:
```sh
["INFO" - 3:25:28 AM] Formatting file:///Users/guilherme/workspace/personal/digital-garden/src/components/Card.astro
["ERROR" - 3:25:28 AM] Error resolving prettier configuration for /Users/guilherme/workspace/personal/digital-garden/src/components/Card.astro
["ERROR" - 3:25:28 AM] require() of ES Module /Users/guilherme/workspace/personal/digital-garden/.prettierrc.js from /Users/guilherme/.vscode/extensions/esbenp.prettier-vscode-9.9.0/node_modules/prettier/third-party.js not supported.
.prettierrc.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares …
```
=> chore: use .cjs instead of .js

.changeset/mighty-boats-bow.md, .vscode/settings.json, src/printer/utils.ts, test/fixtures/other/hugging/input.astro, test/fixtures/other/hugging/output.astro
Previously, we'd only specially case not hugging if the last child of a node was an expression, this PR also makes it so we forcefully hug if the last node is a tag, but only for non-components and fragments, as those are still considered block elements
Hugging rules are slightly confusing, eh
Fix #309
Added test
N/A
=> Fix node not hugging their end when the last children was a node

.changeset/clever-planes-try.md, src/printer/embed.ts, src/printer/index.ts, test/fixtures/styles/with-less/input.astro, test/fixtures/styles/with-less/output.astro, test/fixtures/styles/with-styles-and-body-tag/output.astro, test/fixtures/styles/with-unknown/input.astro, test/fixtures/styles/with-unknown/output.astro, test/tests/styles.test.ts
It turns out that Prettier support LESS, so we can format those code blocks as well. Nice!
This PR also makes it so we ignore style blocks we don't understand, as previously we'd crash on them
Fix https://github.com/withastro/prettier-plugin-astro/issues/317
Added tests for this. Also re-enabled an old disabled test that was disabled due to a compiler isu
N/A
=> fix(css): Add support for formatting LESS style blocks

.changeset/silent-apricots-sniff.md, rollup.config.mjs, src/printer/embed.ts, test/fixtures/styles/with-unknown/input.astro, test/fixtures/styles/with-unknown/output.astro
Fixes #323.
Uses `Buffer` to correctly locate an AST node.
Complements the test case of unknown style preprocessor with a template which contains special characters, thus it won't pass without the changes in this PR.
Bug fix only.
=> fix: treat offset as bytes

.changeset/four-rabbits-destroy.md, src/printer/embed.ts, test/fixtures/return/return-arrow-parens-avoid/input.astro, test/fixtures/return/return-arrow-parens-avoid/options.json, test/fixtures/return/return-arrow-parens-avoid/output.astro, test/fixtures/return/return-basic/input.astro, test/fixtures/return/return-basic/options.json, test/fixtures/return/return-basic/output.astro, test/fixtures/return/return-bracket-spacing-false/input.astro, test/fixtures/return/return-bracket-spacing-false/options.json, test/fixtures/return/return-bracket-spacing-false/output.astro, test/fixtures/return/return-semicolon-false/input.astro, test/fixtures/return/return-semicolon-false/options.json, test/fixtures/return/return-semicolon-false/output.astro, test/fixtures/return/return-single-quote-true/input.astro, test/fixtures/return/return-single-quote-true/options.json, test/fixtures/return/return-single-quote-true/output.astro, test/fixtures/return/return-trailing-comma-all/input.astro, test/fixtures/return/return-trailing-comma-all/options.json, test/fixtures/return/return-trailing-comma-all/output.astro, test/fixtures/return/return-trailing-comma-none/input.astro, test/fixtures/return/return-trailing-comma-none/options.json, test/fixtures/return/return-trailing-comma-none/output.astro, test/tests/return.test.ts
Fixes #326 
Before, prettier-plugin-astro would pass frontmatter as-is to prettier's typescript formatter. This would break plugins that parse the typescript if there are any top-level returns in the frontmatter, as top-level returns are not valid javascript.
This change 
- adds a marker before all `return` statements in Astro frontmatter
- changes `return` to `throw`
- runs the typescript prettier on the modified frontmatter
- finds the marker to turn the `throw`s back to `return`s
- removes the marker
- cleans up any comments that were modified
It's a pretty ugly hack and I'm not proud of it, but it seemingly gets the job done. I expect there is some input on which it will break horribly.
As a note, I did try using a comment as a marker but that breaks if a user uses "return" as a word …
=> Add compatibility for other plugins parsing top-level returns in Astro frontmatter

.changeset/brown-roses-divide.md, .vscode/settings.json, src/printer/embed.ts, test/fixtures/return/return-arrow-parens-avoid/input.astro, test/fixtures/return/return-arrow-parens-avoid/output.astro, test/fixtures/return/return-basic/input.astro, test/fixtures/return/return-basic/output.astro, test/fixtures/return/return-bracket-spacing-false/input.astro, test/fixtures/return/return-bracket-spacing-false/output.astro, test/fixtures/return/return-semicolon-false/input.astro, test/fixtures/return/return-semicolon-false/output.astro, test/fixtures/return/return-single-quote-true/input.astro, test/fixtures/return/return-single-quote-true/output.astro, test/fixtures/return/return-trailing-comma-all/input.astro, test/fixtures/return/return-trailing-comma-all/output.astro, test/fixtures/return/return-trailing-comma-none/input.astro, test/fixtures/return/return-trailing-comma-none/output.astro, test/tests/errors.test.ts
This PR makes it so we use the `babel-ts` parser for the frontmatter, much like we already did for expressions. The differences between the two parsers are not *that* big (case in point: all of our tests passed without changes), but some things can be slightly different at times. Still, since we use that parser already in other places, I figure that now the experience will be more consistant at least
Fix https://github.com/withastro/prettier-plugin-astro/issues/340
Tests still pass + updated tests with formatting changes.
N/A
=> Use `babel-ts` to parse the frontmatter

.changeset/great-peaches-chew.md, src/printer/embed.ts, src/printer/utils.ts, test/fixtures/other/script-types/input.astro, test/fixtures/other/script-types/output.astro, test/tests/other.test.ts
Some script tags are not JavaScript, and that's okay. I think
Fix https://github.com/withastro/prettier-plugin-astro/issues/335
Added a test
N/A
=> feat(embed): Add support for formatting JSON, Markdown etc script tags

.changeset/dirty-ladybugs-float.md, package.json, pnpm-lock.yaml, rollup.config.mjs, src/index.ts, src/options.ts, src/printer/embed.ts, src/printer/index.ts, src/printer/nodes.ts, src/printer/utils.ts, tsconfig.json, workers/parse-worker.js, workers/serialize-worker.js
**Blocked by https://github.com/withastro/compiler/pull/800**
Use the compiler's sync entrypoint. Removing the need for `synckit` completely, making the Prettier plugin faster and lighter! 
Tests should still pass!
N/A
=> feat: use sync version of the compiler

.github/workflows/congrats.yml
- Adds our Discord congrats bot to this merges in this repo.
- Posts in `#dev-tooling` on Discord (I was able to add the secret to this repo myself).
- Uses a set of flower emoji to distinguish messages from language-tools messages in that channel:
- Will be posted by Prettierston:
Same action we use in other repos
N/A
=> Add congrats bot

.changeset/six-spies-roll.md, package.json
removes pnpm from engines, as it is not a javascript engine.
N/A
N/A
=> chore(package.json): remove pnpm from engines

README.md
Prettier support ESM configs now and requires plugins to be specified a bit differently
N/A
It's all docs!
=> docs: update README for Prettier 3 ESM configs

.changeset/grumpy-ears-chew.md, src/printer/index.ts, test/fixtures/basic/basic-html/output.astro, test/fixtures/other/doctype-with-embedded-expr/output.astro, test/fixtures/other/doctype-with-extra-attributes/output.astro, test/fixtures/other/fragment/output.astro
Prettier 3.0 changed doctype to be lowercase. This PR changes prettier-plugin-astro to also set a lowercase doctype.
https://prettier.io/blog/2023/07/05/3.0.0.html#print-html5-doctype-in-lowercase-7391httpsgithubcomprettierprettierpull7391-by-fiskerhttpsgithubcomfisker
Test fixtures were updated for the expected output of lowercase doctype. There is one test fixture that was already commented out, but I updated it as well in case it is ever used again.
This is documented in the Prettier docs.
=> Format doctype as lowercase to match Prettier 3.0

.github/actions/install/action.yml, .github/workflows/ci.yml, .github/workflows/format.yml
CI was still on Node 16
We'll see!
N/A
=> ci: run CI on latest Node versions

.changeset/mean-planets-deliver.md, src/printer/embed.ts, src/printer/utils.ts, test/fixtures/other/non-jsx-compatible-characters/input.astro, test/fixtures/other/non-jsx-compatible-characters/output.astro
What the title says. We were trying to make spread attributes compatible, but we don't need to because they're already valid JavaScript
Fix https://github.com/withastro/prettier-plugin-astro/issues/383
Updated tests to test for more cases
N/A
=> Fix attributes using optional chaining not formatting correctly

.changeset/shy-olives-count.md, CONTRIBUTING.md, src/printer/elements.ts
Hi, while trying it out I stumbled upon this.
1. `CONTRIBUTING.md` `test:w` command renamed to `test:watch` following https://github.com/withastro/prettier-plugin-astro/commit/05f8e2df2ccddf4c488ebb624737eb0818556854#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R34
2. Replaced broken links on `elements.ts` with archived version, PRs for reference:
MDN: https://www.github.com/mdn/content/pull/25891/files#diff-27a6658f50aeee036c920e40bcb54176d2c5a1989935299c6d6fa5897dcb799d
Prettier:  https://www.github.com/prettier/prettier/pull/14110/files#diff-1c305ad8dbf49f559152ee113c75972777ebc5ed0d8b0f04e91203d8b2324156
No testing is needed
No docs update needed
=> Fix: typo in `CONTRIBUTING.md` and broken links on `elements.ts`

.changeset/violet-days-attend.md, src/printer/embed.ts, test/fixtures/other/expression-multiple-roots-stress/input.astro, test/fixtures/other/expression-multiple-roots-stress/output.astro, test/tests/other.test.ts
Much like the average family, we were not properly accounting for middle childs, oops.
Fix https://github.com/withastro/prettier-plugin-astro/issues/387
Added a test!
N/A
=> fix: format JSX expressions with 3+ roots

.changeset/khaki-parrots-yawn.md, src/printer/index.ts, src/printer/utils.ts, test/fixtures/basic/html-custom-elements/output.astro, test/fixtures/markdown/embedded-in-markdown/input.md, test/fixtures/other/fragment/input.astro, test/fixtures/other/fragment/output.astro
Previously, components, fragments and custom elements were considered to be block elements, this is kinda incorrect as they're all whitespace sensitive by default.
In the future, a better way would be to be CSS-based, like Prettier itself is. But that's a much larger refactor.
Fix https://github.com/withastro/prettier-plugin-astro/issues/352
Updated tests for this
N/A
=> fix: hug when needed for components and fragments

README.md
Some users complained about the README being unclear, this hopefully helps with that
N/A
It's docs!
=> fix: rewrite readme

.changeset/thirty-rockets-confess.md, README.md, src/options.ts, src/printer/embed.ts, test/fixtures/options/option-astro-allow-skip-frontmatter-true/input.astro, test/fixtures/options/option-astro-allow-skip-frontmatter-true/options.json, test/fixtures/options/option-astro-allow-skip-frontmatter-true/output.astro
I know this is a very specific use case, but I thought: Why not? Maybe someone else will find useful.
- Adds a new option called "astroSkipFrontmatter" that preserves the content of the front matter. Useful for when the developer wants to format only the template.
- This is useful for integrating with other tools like Biome (https://biomejs.dev) that can format and lint Astro's frontmatter but not the template/html (yet). 
My use case: I added a new script to my package.json that can format all my astro components without interfering with BIome's onSave lint/format.
- Added fixtures for the new option
- Did not add tests for it, since all the other tests for previous options were commented out.
- Added new section on README.md describing the option.
Thanks!
=> [FEAT] Add option to skip formatting the Frontmatter

README.md
This PR add the `pnpm` installation alternative to the documentation (`README.md`).
N/A
- `pnpm` installation alternative added.
=> doc: add `pnpm` installation alternative

.changeset/slimy-plums-learn.md, src/printer/utils.ts, test/fixtures/options/option-html-whitespace-sensitivity-ignore-component/input.astro, test/fixtures/options/option-html-whitespace-sensitivity-ignore-component/options.json, test/fixtures/options/option-html-whitespace-sensitivity-ignore-component/output.astro, test/tests/options.test.ts
Consistently treat custom element & components the same way as HTML elements when `htmlWhitespaceSensitivity` is set to `ignore`, e.g.
Input:
```
<Link href="https://github.com/withastro/prettier-plugin-astro">Prettier Plugin for Astro (using component)</Link>
```
Before:
```
<Link href="https://github.com/withastro/prettier-plugin-astro"
>Prettier Plugin for Astro (using component)</Link
>
```
After
```
<Link href="https://github.com/withastro/prettier-plugin-astro">
Prettier Plugin for Astro (using component)
</Link>
```
Test added
Not needed
=> Format custom elements & components as block elements with htmlWhitespaceSensitivity: ignore
